config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "orgs#index"

  resources :orgs, only: :index, to: redirect { |p, req|
   place = req.params[:place].present? ? "/#{req.params[:place].parameterize}" : ""
   filters = req.params[:filters].present? ? "/#{req.params[:filters]&.join("/")}" : ""
   "/search#{place}#{filters}"
  }

  get "/fiche", "/fiche/*filters/:id", to: "orgs#show"

  get "/search", "/search/*filters", to: "orgs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/slug_concern.rb
module SlugConcern
  extend ActiveSupport::Concern

  included do
    before_validation :generate_slug
    validates :slug, presence: true, uniqueness: true
  end

  private
    def generate_slug
      self.slug = name.parameterize
    end
end

app/models/org.rb
class Org < ApplicationRecord
  paginates_per 10

  has_one :org_place
  has_one :place, through: :org_place
  accepts_nested_attributes_for :place
  has_many :org_searchable_attributes, dependent: :destroy
  has_many :searchable_attributes, through: :org_searchable_attributes

  include SlugConcern
  extend Geocoder::Model::ActiveRecord
  geocoded_by"places.address"
  reverse_geocoded_by "places.latitude", "places.longitude"
end

app/models/org_place.rb
class OrgPlace < ApplicationRecord
  belongs_to :org
  belongs_to :place
end

app/models/org_searchable_attribute.rb
class OrgSearchableAttribute < ApplicationRecord
  belongs_to :org
  belongs_to :searchable_attribute
end

app/models/place.rb
class Place < ApplicationRecord
  has_one :org_place
  has_one :org, through: :org_place

  extend Geocoder::Model::ActiveRecord
  geocoded_by :address
  # after_validation :geocode, if: ->(obj){ obj.address.present? && obj.address_changed? }
end

app/models/searchable_attribute.rb
class SearchableAttribute < ApplicationRecord
  belongs_to :searchable_attribute_category
  has_many :org_searchable_attributes, dependent: :destroy
  has_many :orgs, through: :org_searchable_attributes

  include SlugConcern

  scope :mandatories, -> { joins(:searchable_attribute_category).where(searchable_attribute_categories: {mandatory: true}) }
  scope :optionals, -> { joins(:searchable_attribute_category).where(searchable_attribute_categories: {mandatory: false}) }
end

app/models/searchable_attribute_category.rb
class SearchableAttributeCategory < ApplicationRecord
  has_many :searchable_attributes, dependent: :destroy

  include SlugConcern
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
  before_action :sort_filters, only: [:index]

  def index
    search = Search.new(place: @place, filters: @filters)
    @orgs = search.results.page(params[:page])
    @searchable_categories = SearchableAttributeCategory.all
  end

  def show
    @org = Org.find_by(slug: params[:id])

    redirect_to root_path unless @org
  end

  private
    def sort_filters
      @filters = params[:filters].present? ? params[:filters].split("/")&.flatten : nil

      if @filters
        filter = SearchableAttribute.find_by(slug: @filters.first)
        @place = filter.present? ? nil : @filters.first.split("-").join(" ")
      end

      @filters.shift if @place
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_org(org)
    professions = SearchableAttributeCategory.find_by(name: "Profession").searchable_attributes.pluck(:id)
    attributes = org.searchable_attributes.where(id: professions).map { |a| a.name.parameterize }.join("/")
    address = org.place&.address&.parameterize

    link_to org.name, "/fiche/#{attributes}/#{address}/#{org.slug}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsResearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script type="text/javascript"  src="https://maps.googleapis.com/maps/api/js?libraries=places&key=<%= ENV["GOOGLE_MAPS_API_KEY"] %>"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orgs/_results.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col">Name</th>
    <% @searchable_categories.each do |sc| %>
      <th scope="col"><%= sc.name %></th>
    <% end %>
    <th scope="col">Address</th>
  </tr>
  </thead>
  <tbody>
  <% @orgs.each do |org| %>
    <tr>
      <td><%= link_to_org org %></td>
      <% @searchable_categories.each do |sc| %>
        <td>
          <% org.searchable_attributes.
              where(searchable_attribute_category: @searchable_categories.find_by(name: sc.name)).
              each do |s| %>
            <span class="<%= "font-weight-bold" if params[:filters]&.include?(s.slug) %>">
              <%= s.name %>
            </span>
          <% end %>
        </td>
      <% end %>
      <td><%= org.place&.address %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @orgs %>

app/views/orgs/_searchbar.html.erb
<div class="row justify-content-center mb-3">
  <div class="col text-center">
    <%= bootstrap_form_tag url: orgs_path, method: :get do |f| %>
      <%= f.search_field :place, id: "autocomplete_address", hide_label: true, value: @place, placeholder: "Entrez une adresse...", autocomplete: false %>
      <div class="row">
        <% @searchable_categories.each do |c| %>
          <div class="col text-left">
            <%= "#{c.name}: #{"(mandatory)" if c.mandatory}" %> <br>
            <%= collection_check_boxes(nil, :filters, c.searchable_attributes, :slug, :name, include_hidden: false) do |b| %>
              <%= b.check_box checked: params[:filters]&.include?(b.object.slug) %>
              <%= b.label %> <br>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="mb-3">
        <%= link_to "Clear", root_path %>
        <%= f.submit "Search", name: nil, class: "btn btn-primary ml-3" %>
        <%= "Results: #{@orgs.total_count}" %>
      </div>
    <% end %>
  </div>
</div>

app/views/orgs/index.html.erb
<%= javascript_pack_tag("autocomplete.js") %>

<section class="container">
  <div class="row mb-3">
    <div class="col text-center">
      <h1>Search</h1>
    </div>
  </div>

  <%= render "searchbar" %>
</section>

<%= render "results" %>

app/views/orgs/show.html.erb
<%= @org.name %>